import { createInteractionDataSerializer } from "../gameplay/interactionDataSerializer.js";
import { createRenderFxDataSerializer } from "../gameplay/renderFxDataSerializer.js";
import { createSwarmSettingsApplier } from "./swarmSettingsApplier.js";
import { createInteractionSettingsApplier } from "./interactionSettingsApplier.js";
import { createLightingSettingsApplier } from "./lightingSettingsApplier.js";
import { createRenderFxSettingsApplier } from "./renderFxSettingsApplier.js";
import { createPathfindingSettingsApplier } from "./pathfindingSettingsApplier.js";

export function createSettingsLegacyRuntimeBinding(deps) {
  const applySwarmSettingsLegacy = createSwarmSettingsApplier({
    getSwarmSettings: deps.getSwarmSettings,
    swarmEnabledToggle: deps.swarmEnabledToggle,
    swarmLitModeToggle: deps.swarmLitModeToggle,
    swarmFollowZoomToggle: deps.swarmFollowZoomToggle,
    swarmFollowZoomInInput: deps.swarmFollowZoomInInput,
    swarmFollowZoomOutInput: deps.swarmFollowZoomOutInput,
    swarmFollowHawkRangeGizmoToggle: deps.swarmFollowHawkRangeGizmoToggle,
    swarmFollowAgentSpeedSmoothingInput: deps.swarmFollowAgentSpeedSmoothingInput,
    swarmFollowAgentZoomSmoothingInput: deps.swarmFollowAgentZoomSmoothingInput,
    swarmStatsPanelToggle: deps.swarmStatsPanelToggle,
    swarmShowTerrainToggle: deps.swarmShowTerrainToggle,
    swarmBackgroundColorInput: deps.swarmBackgroundColorInput,
    swarmAgentCountInput: deps.swarmAgentCountInput,
    swarmUpdateIntervalInput: deps.swarmUpdateIntervalInput,
    swarmMaxSpeedInput: deps.swarmMaxSpeedInput,
    swarmSteeringMaxInput: deps.swarmSteeringMaxInput,
    swarmVariationStrengthInput: deps.swarmVariationStrengthInput,
    swarmNeighborRadiusInput: deps.swarmNeighborRadiusInput,
    swarmMinHeightInput: deps.swarmMinHeightInput,
    swarmMaxHeightInput: deps.swarmMaxHeightInput,
    swarmSeparationRadiusInput: deps.swarmSeparationRadiusInput,
    swarmAlignmentWeightInput: deps.swarmAlignmentWeightInput,
    swarmCohesionWeightInput: deps.swarmCohesionWeightInput,
    swarmSeparationWeightInput: deps.swarmSeparationWeightInput,
    swarmWanderWeightInput: deps.swarmWanderWeightInput,
    swarmRestChanceInput: deps.swarmRestChanceInput,
    swarmRestTicksInput: deps.swarmRestTicksInput,
    swarmBreedingThresholdInput: deps.swarmBreedingThresholdInput,
    swarmBreedingSpawnChanceInput: deps.swarmBreedingSpawnChanceInput,
    swarmCursorModeInput: deps.swarmCursorModeInput,
    swarmCursorStrengthInput: deps.swarmCursorStrengthInput,
    swarmCursorRadiusInput: deps.swarmCursorRadiusInput,
    swarmHawkEnabledToggle: deps.swarmHawkEnabledToggle,
    swarmHawkCountInput: deps.swarmHawkCountInput,
    swarmHawkColorInput: deps.swarmHawkColorInput,
    swarmHawkSpeedInput: deps.swarmHawkSpeedInput,
    swarmHawkSteeringInput: deps.swarmHawkSteeringInput,
    swarmHawkTargetRangeInput: deps.swarmHawkTargetRangeInput,
    swarmTimeRoutingInput: deps.swarmTimeRoutingInput,
    swarmFollowTargetInput: deps.swarmFollowTargetInput,
    applySwarmFollowState: deps.applySwarmFollowState,
    swarmState: deps.swarmState,
    normalizeSwarmFollowZoomInputs: deps.normalizeSwarmFollowZoomInputs,
    normalizeSwarmHeightRangeInputs: deps.normalizeSwarmHeightRangeInputs,
    updateSwarmLabels: deps.updateSwarmLabels,
    updateSwarmUi: deps.updateSwarmUi,
    syncSwarmFollowToStore: deps.syncSwarmFollowToStore,
  });

  const serializeInteractionSettings = createInteractionDataSerializer({
    getPathfindingStateSnapshot: deps.getPathfindingStateSnapshot,
    getCursorLightSnapshot: deps.getCursorLightSnapshot,
    getPointLightsState: deps.getPointLightsState,
    clamp: deps.clamp,
  });

  const syncPathfindingSettingsUi = createPathfindingSettingsApplier({
    getPathfindingStateSnapshot: deps.getPathfindingStateSnapshot,
    pathfindingRangeInput: deps.pathfindingRangeInput,
    pathWeightSlopeInput: deps.pathWeightSlopeInput,
    pathWeightHeightInput: deps.pathWeightHeightInput,
    pathWeightWaterInput: deps.pathWeightWaterInput,
    pathSlopeCutoffInput: deps.pathSlopeCutoffInput,
    pathBaseCostInput: deps.pathBaseCostInput,
    updatePathfindingRangeLabel: deps.updatePathfindingRangeLabel,
    updatePathWeightLabels: deps.updatePathWeightLabels,
    updatePathSlopeCutoffLabel: deps.updatePathSlopeCutoffLabel,
    updatePathBaseCostLabel: deps.updatePathBaseCostLabel,
  });

  const applyInteractionSettingsLegacy = createInteractionSettingsApplier({
    syncPathfindingSettingsUi,
    getCursorLightSnapshot: deps.getCursorLightSnapshot,
    applyCursorLightConfigSnapshot: deps.applyCursorLightConfigSnapshot,
    cursorLightState: deps.cursorLightState,
    cursorLightModeToggle: deps.cursorLightModeToggle,
    cursorLightFollowHeightToggle: deps.cursorLightFollowHeightToggle,
    cursorLightColorInput: deps.cursorLightColorInput,
    cursorLightStrengthInput: deps.cursorLightStrengthInput,
    cursorLightHeightOffsetInput: deps.cursorLightHeightOffsetInput,
    cursorLightGizmoToggle: deps.cursorLightGizmoToggle,
    pointLightLiveUpdateToggle: deps.pointLightLiveUpdateToggle,
    isPointLightLiveUpdateEnabled: deps.isPointLightLiveUpdateEnabled,
    updateCursorLightStrengthLabel: deps.updateCursorLightStrengthLabel,
    updateCursorLightHeightOffsetLabel: deps.updateCursorLightHeightOffsetLabel,
    updateCursorLightModeUi: deps.updateCursorLightModeUi,
  });

  const applyLightingSettingsLegacy = createLightingSettingsApplier({
    getCoreState: deps.getCoreState,
    getLightingSettings: deps.getLightingSettings,
    shadowsToggle: deps.shadowsToggle,
    heightScaleInput: deps.heightScaleInput,
    shadowStrengthInput: deps.shadowStrengthInput,
    shadowBlurInput: deps.shadowBlurInput,
    ambientInput: deps.ambientInput,
    diffuseInput: deps.diffuseInput,
    volumetricToggle: deps.volumetricToggle,
    volumetricStrengthInput: deps.volumetricStrengthInput,
    volumetricDensityInput: deps.volumetricDensityInput,
    volumetricAnisotropyInput: deps.volumetricAnisotropyInput,
    volumetricLengthInput: deps.volumetricLengthInput,
    volumetricSamplesInput: deps.volumetricSamplesInput,
    cycleState: deps.cycleState,
    cycleSpeedInput: deps.cycleSpeedInput,
    simTickHoursInput: deps.simTickHoursInput,
    pointFlickerToggle: deps.pointFlickerToggle,
    pointFlickerStrengthInput: deps.pointFlickerStrengthInput,
    pointFlickerSpeedInput: deps.pointFlickerSpeedInput,
    pointFlickerSpatialInput: deps.pointFlickerSpatialInput,
    clamp: deps.clamp,
    normalizeSimTickHours: deps.normalizeSimTickHours,
    updateVolumetricLabels: deps.updateVolumetricLabels,
    updateVolumetricUi: deps.updateVolumetricUi,
    updateShadowBlurLabel: deps.updateShadowBlurLabel,
    updatePointFlickerLabels: deps.updatePointFlickerLabels,
    updatePointFlickerUi: deps.updatePointFlickerUi,
    updateSimTickLabel: deps.updateSimTickLabel,
    setCycleHourSliderFromState: deps.setCycleHourSliderFromState,
    updateCycleHourLabel: deps.updateCycleHourLabel,
    schedulePointLightBake: deps.schedulePointLightBake,
  });

  const renderFxSettingsApplier = createRenderFxSettingsApplier({
    getFogSettings: deps.getFogSettings,
    getParallaxSettings: deps.getParallaxSettings,
    getCloudSettings: deps.getCloudSettings,
    getWaterSettings: deps.getWaterSettings,
    getTimeState: deps.getTimeState,
    fogToggle: deps.fogToggle,
    fogColorInput: deps.fogColorInput,
    setFogColorManual: deps.setFogColorManual,
    fogMinAlphaInput: deps.fogMinAlphaInput,
    fogMaxAlphaInput: deps.fogMaxAlphaInput,
    fogFalloffInput: deps.fogFalloffInput,
    fogStartOffsetInput: deps.fogStartOffsetInput,
    parallaxToggle: deps.parallaxToggle,
    parallaxStrengthInput: deps.parallaxStrengthInput,
    parallaxBandsInput: deps.parallaxBandsInput,
    cloudToggle: deps.cloudToggle,
    cloudCoverageInput: deps.cloudCoverageInput,
    cloudSoftnessInput: deps.cloudSoftnessInput,
    cloudOpacityInput: deps.cloudOpacityInput,
    cloudScaleInput: deps.cloudScaleInput,
    cloudSpeed1Input: deps.cloudSpeed1Input,
    cloudSpeed2Input: deps.cloudSpeed2Input,
    cloudSunParallaxInput: deps.cloudSunParallaxInput,
    cloudSunProjectToggle: deps.cloudSunProjectToggle,
    cloudTimeRoutingInput: deps.cloudTimeRoutingInput,
    waterFxToggle: deps.waterFxToggle,
    waterFlowDownhillToggle: deps.waterFlowDownhillToggle,
    waterFlowInvertDownhillToggle: deps.waterFlowInvertDownhillToggle,
    waterFlowDebugToggle: deps.waterFlowDebugToggle,
    waterFlowDirectionInput: deps.waterFlowDirectionInput,
    waterLocalFlowMixInput: deps.waterLocalFlowMixInput,
    waterDownhillBoostInput: deps.waterDownhillBoostInput,
    waterFlowRadius1Input: deps.waterFlowRadius1Input,
    waterFlowRadius2Input: deps.waterFlowRadius2Input,
    waterFlowRadius3Input: deps.waterFlowRadius3Input,
    waterFlowWeight1Input: deps.waterFlowWeight1Input,
    waterFlowWeight2Input: deps.waterFlowWeight2Input,
    waterFlowWeight3Input: deps.waterFlowWeight3Input,
    waterFlowStrengthInput: deps.waterFlowStrengthInput,
    waterFlowSpeedInput: deps.waterFlowSpeedInput,
    waterFlowScaleInput: deps.waterFlowScaleInput,
    waterShimmerStrengthInput: deps.waterShimmerStrengthInput,
    waterGlintStrengthInput: deps.waterGlintStrengthInput,
    waterGlintSharpnessInput: deps.waterGlintSharpnessInput,
    waterShoreFoamStrengthInput: deps.waterShoreFoamStrengthInput,
    waterShoreWidthInput: deps.waterShoreWidthInput,
    waterReflectivityInput: deps.waterReflectivityInput,
    waterTintColorInput: deps.waterTintColorInput,
    waterTintStrengthInput: deps.waterTintStrengthInput,
    waterTimeRoutingInput: deps.waterTimeRoutingInput,
    clamp: deps.clamp,
    normalizeRoutingMode: deps.normalizeRoutingMode,
    rgbToHex: deps.rgbToHex,
    updateFogAlphaLabels: deps.updateFogAlphaLabels,
    updateFogFalloffLabel: deps.updateFogFalloffLabel,
    updateFogStartOffsetLabel: deps.updateFogStartOffsetLabel,
    updateFogUi: deps.updateFogUi,
    updateParallaxStrengthLabel: deps.updateParallaxStrengthLabel,
    updateParallaxBandsLabel: deps.updateParallaxBandsLabel,
    updateParallaxUi: deps.updateParallaxUi,
    updateCloudLabels: deps.updateCloudLabels,
    updateCloudUi: deps.updateCloudUi,
    updateWaterLabels: deps.updateWaterLabels,
    updateWaterUi: deps.updateWaterUi,
    rebuildFlowMapTexture: deps.rebuildFlowMapTexture,
  });

  const renderFxDataSerializer = createRenderFxDataSerializer({
    getCoreState: deps.getCoreState,
    getLightingSettings: deps.getLightingSettings,
    getFogSettings: deps.getFogSettings,
    getParallaxSettings: deps.getParallaxSettings,
    getCloudSettings: deps.getCloudSettings,
    getWaterSettings: deps.getWaterSettings,
    getTimeState: deps.getTimeState,
    cycleState: deps.cycleState,
    getConfiguredSimTickHours: deps.getConfiguredSimTickHours,
    clamp: deps.clamp,
    clampRound: deps.clampRound,
    normalizeRoutingMode: deps.normalizeRoutingMode,
    rgbToHex: deps.rgbToHex,
  });

  return {
    applySwarmSettingsLegacy,
    serializeSwarmDataLegacy: deps.serializeSwarmDataLegacy,
    applySwarmData: deps.applySwarmData,
    syncPathfindingSettingsUi,
    serializeInteractionSettings,
    applyInteractionSettingsLegacy,
    applyLightingSettingsLegacy,
    applyFogSettingsLegacy: renderFxSettingsApplier.applyFogSettingsLegacy,
    applyParallaxSettingsLegacy: renderFxSettingsApplier.applyParallaxSettingsLegacy,
    applyCloudSettingsLegacy: renderFxSettingsApplier.applyCloudSettingsLegacy,
    applyWaterSettingsLegacy: renderFxSettingsApplier.applyWaterSettingsLegacy,
    serializeLightingSettingsLegacy: renderFxDataSerializer.serializeLightingSettingsLegacy,
    serializeFogSettingsLegacy: renderFxDataSerializer.serializeFogSettingsLegacy,
    serializeParallaxSettingsLegacy: renderFxDataSerializer.serializeParallaxSettingsLegacy,
    serializeCloudSettingsLegacy: renderFxDataSerializer.serializeCloudSettingsLegacy,
    serializeWaterSettingsLegacy: renderFxDataSerializer.serializeWaterSettingsLegacy,
  };
}
