import { runStartupUiSync } from "./startupUiSync.js";

export function runStartupUiSyncRuntime(deps) {
  runStartupUiSync({
    setSwarmDefaults: deps.setSwarmDefaults,
    normalizeSwarmHeightRangeInputs: deps.normalizeSwarmHeightRangeInputs,
    updatePathfindingRangeLabel: deps.updatePathfindingRangeLabel,
    updatePathWeightLabels: deps.updatePathWeightLabels,
    updatePathSlopeCutoffLabel: deps.updatePathSlopeCutoffLabel,
    updatePathBaseCostLabel: deps.updatePathBaseCostLabel,
    updateSwarmLabels: deps.updateSwarmLabels,
    updateSwarmUi: deps.updateSwarmUi,
    updateSwarmStatsPanel: deps.updateSwarmStatsPanel,
    updateSwarmFollowButtonUi: deps.updateSwarmFollowButtonUi,
    updateParallaxStrengthLabel: deps.updateParallaxStrengthLabel,
    updateParallaxBandsLabel: deps.updateParallaxBandsLabel,
    updateShadowBlurLabel: deps.updateShadowBlurLabel,
    updateVolumetricLabels: deps.updateVolumetricLabels,
    updatePointFlickerLabels: deps.updatePointFlickerLabels,
    updateSimTickLabel: deps.updateSimTickLabel,
    updateFogAlphaLabels: deps.updateFogAlphaLabels,
    updateFogFalloffLabel: deps.updateFogFalloffLabel,
    updateFogStartOffsetLabel: deps.updateFogStartOffsetLabel,
    updateCloudLabels: deps.updateCloudLabels,
    updateWaterLabels: deps.updateWaterLabels,
    updatePointLightStrengthLabel: deps.updatePointLightStrengthLabel,
    updatePointLightIntensityLabel: deps.updatePointLightIntensityLabel,
    updatePointLightHeightOffsetLabel: deps.updatePointLightHeightOffsetLabel,
    updatePointLightFlickerLabel: deps.updatePointLightFlickerLabel,
    updatePointLightFlickerSpeedLabel: deps.updatePointLightFlickerSpeedLabel,
    updateCursorLightStrengthLabel: deps.updateCursorLightStrengthLabel,
    updateCursorLightHeightOffsetLabel: deps.updateCursorLightHeightOffsetLabel,
    setCycleHourSliderFromState: deps.setCycleHourSliderFromState,
    updateCycleHourLabel: deps.updateCycleHourLabel,
    syncMapPathInput: deps.syncMapPathInput,
    currentMapFolderPath: deps.currentMapFolderPath,
    updateLightEditorUi: deps.updateLightEditorUi,
    updateCursorLightModeUi: deps.updateCursorLightModeUi,
    updateParallaxUi: deps.updateParallaxUi,
    updateVolumetricUi: deps.updateVolumetricUi,
    updatePointFlickerUi: deps.updatePointFlickerUi,
    updateFogUi: deps.updateFogUi,
    updateCloudUi: deps.updateCloudUi,
    updateWaterUi: deps.updateWaterUi,
    setActiveTopic: deps.setActiveTopic,
    setInteractionMode: deps.setInteractionMode,
    updateModeCapabilitiesUi: deps.updateModeCapabilitiesUi,
    reseedSwarmAgents: deps.reseedSwarmAgents,
    getSwarmSettings: deps.getSwarmSettings,
    setStatus: deps.setStatus,
    statusTextEl: deps.statusTextEl,
  });
}
