export function createSwarmStateUiFacadeRuntime(deps) {
  return {
    getSwarmCursorMode: (...args) => deps.getMainRuntimeStateBinding().getSwarmCursorMode(...args),
    getSwarmSettings: (...args) => deps.getMainRuntimeStateBinding().getSwarmSettings(...args),
    getPathfindingStateSnapshot: (...args) => deps.getMainRuntimeStateBinding().getPathfindingStateSnapshot(...args),
    syncMapStateToStore: (...args) => deps.getMainRuntimeStateBinding().syncMapStateToStore(...args),
    syncPointLightsStateToStore: (...args) => deps.getMainRuntimeStateBinding().syncPointLightsStateToStore(...args),
    getCursorLightSnapshot: (...args) => deps.getMainRuntimeStateBinding().getCursorLightSnapshot(...args),
    isPointLightLiveUpdateEnabled: (...args) => deps.getMainRuntimeStateBinding().isPointLightLiveUpdateEnabled(...args),
    isPointLightsSaveConfirmArmed: (...args) => deps.getMainRuntimeStateBinding().isPointLightsSaveConfirmArmed(...args),
    setSwarmDefaults: (...args) => deps.getMainRuntimeStateBinding().setSwarmDefaults(...args),
    isSwarmEnabled: (...args) => deps.getMainRuntimeStateBinding().isSwarmEnabled(...args),
    normalizeSwarmHeightRangeInputs: (...args) => deps.swarmUiRuntimeBinding.normalizeSwarmHeightRangeInputs(...args),
    normalizeSwarmFollowZoomInputs: (...args) => deps.swarmUiRuntimeBinding.normalizeSwarmFollowZoomInputs(...args),
    updateSwarmLabels: (...args) => deps.swarmUiRuntimeBinding.updateSwarmLabels(...args),
    updateSwarmUi: (...args) => deps.swarmUiRuntimeBinding.updateSwarmUi(...args),
    updateSwarmStatsPanel: (...args) => deps.swarmUiRuntimeBinding.updateSwarmStatsPanel(...args),
    updateSwarmFollowButtonUi: (...args) => deps.swarmUiRuntimeBinding.updateSwarmFollowButtonUi(...args),
    syncSwarmSettingsInputs: (...args) => deps.swarmUiRuntimeBinding.syncSwarmSettingsInputs(...args),
    syncSwarmPanelUi: (...args) => deps.swarmUiRuntimeBinding.syncSwarmPanelUi(...args),
    syncSimTickHoursInput: (...args) => deps.swarmUiRuntimeBinding.syncSimTickHoursInput(...args),
    syncCycleSpeedInput: (...args) => deps.swarmUiRuntimeBinding.syncCycleSpeedInput(...args),
    syncRoutingInput: (...args) => deps.swarmUiRuntimeBinding.syncRoutingInput(...args),
  };
}
