import { createSwarmInputNormalization } from "./swarmInputNormalization.js";
import { createSwarmPanelUi } from "./swarmPanelUi.js";
import { createSwarmSettingsSyncRuntime } from "./swarmSettingsSyncRuntime.js";
import { createTimeRoutingSettingsSyncRuntime } from "./timeRoutingSettingsSyncRuntime.js";

export function createSwarmUiRuntimeBinding(deps) {
  const { mainRuntimeStateBinding } = deps;

  const swarmInputNormalization = createSwarmInputNormalization({
    clamp: deps.clamp,
    swarmMinHeightInput: deps.swarmMinHeightInput,
    swarmMaxHeightInput: deps.swarmMaxHeightInput,
    swarmFollowZoomInInput: deps.swarmFollowZoomInInput,
    swarmFollowZoomOutInput: deps.swarmFollowZoomOutInput,
    swarmHeightMax: deps.swarmZMax,
    zoomMin: deps.zoomMin,
    zoomMax: deps.zoomMax,
  });

  const swarmPanelUi = createSwarmPanelUi({
    getSwarmSettings: () => mainRuntimeStateBinding.getSwarmSettings(),
    swarmState: deps.swarmState,
    getSwarmFollowSnapshot: deps.getSwarmFollowSnapshot,
    swarmFollowToggleBtn: deps.swarmFollowToggleBtn,
    swarmStatsPanelEl: deps.swarmStatsPanelEl,
    swarmStatsBirdsValue: deps.swarmStatsBirdsValue,
    swarmStatsHawksValue: deps.swarmStatsHawksValue,
    swarmStatsStepsValue: deps.swarmStatsStepsValue,
    swarmStatsAvgHawkKillValue: deps.swarmStatsAvgHawkKillValue,
    swarmAgentCountValue: deps.swarmAgentCountValue,
    swarmFollowZoomInValue: deps.swarmFollowZoomInValue,
    swarmFollowZoomOutValue: deps.swarmFollowZoomOutValue,
    swarmFollowAgentSpeedSmoothingValue: deps.swarmFollowAgentSpeedSmoothingValue,
    swarmFollowAgentZoomSmoothingValue: deps.swarmFollowAgentZoomSmoothingValue,
    swarmUpdateIntervalValue: deps.swarmUpdateIntervalValue,
    swarmMaxSpeedValue: deps.swarmMaxSpeedValue,
    swarmSteeringMaxValue: deps.swarmSteeringMaxValue,
    swarmVariationStrengthValue: deps.swarmVariationStrengthValue,
    swarmNeighborRadiusValue: deps.swarmNeighborRadiusValue,
    swarmMinHeightValue: deps.swarmMinHeightValue,
    swarmMaxHeightValue: deps.swarmMaxHeightValue,
    swarmSeparationRadiusValue: deps.swarmSeparationRadiusValue,
    swarmAlignmentWeightValue: deps.swarmAlignmentWeightValue,
    swarmCohesionWeightValue: deps.swarmCohesionWeightValue,
    swarmSeparationWeightValue: deps.swarmSeparationWeightValue,
    swarmWanderWeightValue: deps.swarmWanderWeightValue,
    swarmRestChanceValue: deps.swarmRestChanceValue,
    swarmRestTicksValue: deps.swarmRestTicksValue,
    swarmBreedingThresholdValue: deps.swarmBreedingThresholdValue,
    swarmBreedingSpawnChanceValue: deps.swarmBreedingSpawnChanceValue,
    swarmCursorStrengthValue: deps.swarmCursorStrengthValue,
    swarmCursorRadiusValue: deps.swarmCursorRadiusValue,
    swarmHawkCountValue: deps.swarmHawkCountValue,
    swarmHawkSpeedValue: deps.swarmHawkSpeedValue,
    swarmHawkSteeringValue: deps.swarmHawkSteeringValue,
    swarmHawkTargetRangeValue: deps.swarmHawkTargetRangeValue,
    swarmShowTerrainToggle: deps.swarmShowTerrainToggle,
    swarmLitModeToggle: deps.swarmLitModeToggle,
    swarmFollowTargetInput: deps.swarmFollowTargetInput,
    swarmFollowZoomToggle: deps.swarmFollowZoomToggle,
    swarmFollowZoomInInput: deps.swarmFollowZoomInInput,
    swarmFollowZoomOutInput: deps.swarmFollowZoomOutInput,
    swarmFollowHawkRangeGizmoToggle: deps.swarmFollowHawkRangeGizmoToggle,
    swarmFollowAgentSpeedSmoothingInput: deps.swarmFollowAgentSpeedSmoothingInput,
    swarmFollowAgentZoomSmoothingInput: deps.swarmFollowAgentZoomSmoothingInput,
    swarmStatsPanelToggle: deps.swarmStatsPanelToggle,
    swarmBackgroundColorInput: deps.swarmBackgroundColorInput,
    swarmAgentCountInput: deps.swarmAgentCountInput,
    swarmUpdateIntervalInput: deps.swarmUpdateIntervalInput,
    swarmMaxSpeedInput: deps.swarmMaxSpeedInput,
    swarmSteeringMaxInput: deps.swarmSteeringMaxInput,
    swarmVariationStrengthInput: deps.swarmVariationStrengthInput,
    swarmNeighborRadiusInput: deps.swarmNeighborRadiusInput,
    swarmMinHeightInput: deps.swarmMinHeightInput,
    swarmMaxHeightInput: deps.swarmMaxHeightInput,
    swarmSeparationRadiusInput: deps.swarmSeparationRadiusInput,
    swarmAlignmentWeightInput: deps.swarmAlignmentWeightInput,
    swarmCohesionWeightInput: deps.swarmCohesionWeightInput,
    swarmSeparationWeightInput: deps.swarmSeparationWeightInput,
    swarmWanderWeightInput: deps.swarmWanderWeightInput,
    swarmRestChanceInput: deps.swarmRestChanceInput,
    swarmRestTicksInput: deps.swarmRestTicksInput,
    swarmBreedingThresholdInput: deps.swarmBreedingThresholdInput,
    swarmBreedingSpawnChanceInput: deps.swarmBreedingSpawnChanceInput,
    swarmCursorModeInput: deps.swarmCursorModeInput,
    swarmCursorStrengthInput: deps.swarmCursorStrengthInput,
    swarmCursorRadiusInput: deps.swarmCursorRadiusInput,
    swarmHawkEnabledToggle: deps.swarmHawkEnabledToggle,
    swarmHawkCountInput: deps.swarmHawkCountInput,
    swarmHawkColorInput: deps.swarmHawkColorInput,
    swarmHawkSpeedInput: deps.swarmHawkSpeedInput,
    swarmHawkSteeringInput: deps.swarmHawkSteeringInput,
    swarmHawkTargetRangeInput: deps.swarmHawkTargetRangeInput,
  });

  const swarmSettingsSyncRuntime = createSwarmSettingsSyncRuntime({
    getSwarmSettings: () => mainRuntimeStateBinding.getSwarmSettings(),
    swarmEnabledToggle: deps.swarmEnabledToggle,
    swarmLitModeToggle: deps.swarmLitModeToggle,
    swarmFollowZoomToggle: deps.swarmFollowZoomToggle,
    swarmFollowZoomInInput: deps.swarmFollowZoomInInput,
    swarmFollowZoomOutInput: deps.swarmFollowZoomOutInput,
    swarmFollowHawkRangeGizmoToggle: deps.swarmFollowHawkRangeGizmoToggle,
    swarmFollowAgentSpeedSmoothingInput: deps.swarmFollowAgentSpeedSmoothingInput,
    swarmFollowAgentZoomSmoothingInput: deps.swarmFollowAgentZoomSmoothingInput,
    swarmStatsPanelToggle: deps.swarmStatsPanelToggle,
    swarmShowTerrainToggle: deps.swarmShowTerrainToggle,
    swarmBackgroundColorInput: deps.swarmBackgroundColorInput,
    swarmAgentCountInput: deps.swarmAgentCountInput,
    swarmUpdateIntervalInput: deps.swarmUpdateIntervalInput,
    swarmMaxSpeedInput: deps.swarmMaxSpeedInput,
    swarmSteeringMaxInput: deps.swarmSteeringMaxInput,
    swarmVariationStrengthInput: deps.swarmVariationStrengthInput,
    swarmNeighborRadiusInput: deps.swarmNeighborRadiusInput,
    swarmMinHeightInput: deps.swarmMinHeightInput,
    swarmMaxHeightInput: deps.swarmMaxHeightInput,
    swarmSeparationRadiusInput: deps.swarmSeparationRadiusInput,
    swarmAlignmentWeightInput: deps.swarmAlignmentWeightInput,
    swarmCohesionWeightInput: deps.swarmCohesionWeightInput,
    swarmSeparationWeightInput: deps.swarmSeparationWeightInput,
    swarmWanderWeightInput: deps.swarmWanderWeightInput,
    swarmRestChanceInput: deps.swarmRestChanceInput,
    swarmRestTicksInput: deps.swarmRestTicksInput,
    swarmBreedingThresholdInput: deps.swarmBreedingThresholdInput,
    swarmBreedingSpawnChanceInput: deps.swarmBreedingSpawnChanceInput,
    swarmCursorModeInput: deps.swarmCursorModeInput,
    swarmCursorStrengthInput: deps.swarmCursorStrengthInput,
    swarmCursorRadiusInput: deps.swarmCursorRadiusInput,
    swarmHawkEnabledToggle: deps.swarmHawkEnabledToggle,
    swarmHawkCountInput: deps.swarmHawkCountInput,
    swarmHawkColorInput: deps.swarmHawkColorInput,
    swarmHawkSpeedInput: deps.swarmHawkSpeedInput,
    swarmHawkSteeringInput: deps.swarmHawkSteeringInput,
    swarmHawkTargetRangeInput: deps.swarmHawkTargetRangeInput,
    swarmTimeRoutingInput: deps.swarmTimeRoutingInput,
    updateSwarmLabels: swarmPanelUi.updateSwarmLabels,
    updateSwarmUi: swarmPanelUi.updateSwarmUi,
  });

  const timeRoutingSettingsSyncRuntime = createTimeRoutingSettingsSyncRuntime({
    swarmTimeRoutingInput: deps.swarmTimeRoutingInput,
    cloudTimeRoutingInput: deps.cloudTimeRoutingInput,
    waterTimeRoutingInput: deps.waterTimeRoutingInput,
    simTickHoursInput: deps.simTickHoursInput,
    cycleSpeedInput: deps.cycleSpeedInput,
  });

  return {
    getSwarmCursorMode: () => mainRuntimeStateBinding.getSwarmCursorMode(),
    getSwarmSettings: () => mainRuntimeStateBinding.getSwarmSettings(),
    getPathfindingStateSnapshot: () => mainRuntimeStateBinding.getPathfindingStateSnapshot(),
    syncMapStateToStore: () => mainRuntimeStateBinding.syncMapStateToStore(),
    syncPointLightsStateToStore: (nextLiveUpdate = null, nextSaveConfirmArmed = null) =>
      mainRuntimeStateBinding.syncPointLightsStateToStore(nextLiveUpdate, nextSaveConfirmArmed),
    getCursorLightSnapshot: () => mainRuntimeStateBinding.getCursorLightSnapshot(),
    isPointLightLiveUpdateEnabled: () => mainRuntimeStateBinding.isPointLightLiveUpdateEnabled(),
    isPointLightsSaveConfirmArmed: () => mainRuntimeStateBinding.isPointLightsSaveConfirmArmed(),
    setSwarmDefaults: () => mainRuntimeStateBinding.setSwarmDefaults(),
    isSwarmEnabled: () => mainRuntimeStateBinding.isSwarmEnabled(),
    normalizeSwarmHeightRangeInputs: (...args) => swarmInputNormalization.normalizeSwarmHeightRangeInputs(...args),
    normalizeSwarmFollowZoomInputs: (...args) => swarmInputNormalization.normalizeSwarmFollowZoomInputs(...args),
    updateSwarmLabels: () => swarmPanelUi.updateSwarmLabels(),
    updateSwarmUi: () => swarmPanelUi.updateSwarmUi(),
    updateSwarmStatsPanel: () => swarmPanelUi.updateSwarmStatsPanel(),
    updateSwarmFollowButtonUi: () => swarmPanelUi.updateSwarmFollowButtonUi(),
    syncSwarmSettingsInputs: () => swarmSettingsSyncRuntime.syncSwarmSettingsInputs(),
    syncSwarmPanelUi: () => swarmSettingsSyncRuntime.syncSwarmPanelUi(),
    syncRoutingInput: (...args) => timeRoutingSettingsSyncRuntime.syncRoutingInput(...args),
    syncSimTickHoursInput: (...args) => timeRoutingSettingsSyncRuntime.syncSimTickHoursInput(...args),
    syncCycleSpeedInput: (...args) => timeRoutingSettingsSyncRuntime.syncCycleSpeedInput(...args),
  };
}
