export function createUiFacadeSetupRuntime(uiRuntimeFacade) {
  return {
    updateLightEditorUi: (...args) => uiRuntimeFacade.updateLightEditorUi(...args),
    beginLightEdit: (...args) => uiRuntimeFacade.beginLightEdit(...args),
    applyDraftToSelectedPointLight: (...args) => uiRuntimeFacade.applyDraftToSelectedPointLight(...args),
    rebakeIfPointLightLiveUpdateEnabled: (...args) => uiRuntimeFacade.rebakeIfPointLightLiveUpdateEnabled(...args),
    findPointLightAtPixel: (...args) => uiRuntimeFacade.findPointLightAtPixel(...args),
    createPointLight: (...args) => uiRuntimeFacade.createPointLight(...args),
    getGrayAt: (...args) => uiRuntimeFacade.getGrayAt(...args),
    computeMoveStepCost: (...args) => uiRuntimeFacade.computeMoveStepCost(...args),
    rebuildMovementField: (...args) => uiRuntimeFacade.rebuildMovementField(...args),
    extractPathTo: (...args) => uiRuntimeFacade.extractPathTo(...args),
    refreshPathPreview: (...args) => uiRuntimeFacade.refreshPathPreview(...args),
    updatePathPreviewFromPointer: (...args) => uiRuntimeFacade.updatePathPreviewFromPointer(...args),
    getCurrentPathMetrics: (...args) => uiRuntimeFacade.getCurrentPathMetrics(...args),
    updatePathfindingRangeLabel: (...args) => uiRuntimeFacade.updatePathfindingRangeLabel(...args),
    updatePathWeightLabels: (...args) => uiRuntimeFacade.updatePathWeightLabels(...args),
    updatePathSlopeCutoffLabel: (...args) => uiRuntimeFacade.updatePathSlopeCutoffLabel(...args),
    updatePathBaseCostLabel: (...args) => uiRuntimeFacade.updatePathBaseCostLabel(...args),
    updateParallaxStrengthLabel: (...args) => uiRuntimeFacade.updateParallaxStrengthLabel(...args),
    updateParallaxBandsLabel: (...args) => uiRuntimeFacade.updateParallaxBandsLabel(...args),
    updateShadowBlurLabel: (...args) => uiRuntimeFacade.updateShadowBlurLabel(...args),
    updateSimTickLabel: (...args) => uiRuntimeFacade.updateSimTickLabel(...args),
    updateFogAlphaLabels: (...args) => uiRuntimeFacade.updateFogAlphaLabels(...args),
    updateFogFalloffLabel: (...args) => uiRuntimeFacade.updateFogFalloffLabel(...args),
    updateFogStartOffsetLabel: (...args) => uiRuntimeFacade.updateFogStartOffsetLabel(...args),
    updatePointFlickerLabels: (...args) => uiRuntimeFacade.updatePointFlickerLabels(...args),
    updatePointFlickerUi: (...args) => uiRuntimeFacade.updatePointFlickerUi(...args),
    updateVolumetricLabels: (...args) => uiRuntimeFacade.updateVolumetricLabels(...args),
    updateVolumetricUi: (...args) => uiRuntimeFacade.updateVolumetricUi(...args),
    updateCloudLabels: (...args) => uiRuntimeFacade.updateCloudLabels(...args),
    updateWaterLabels: (...args) => uiRuntimeFacade.updateWaterLabels(...args),
    updateParallaxUi: (...args) => uiRuntimeFacade.updateParallaxUi(...args),
    updateFogUi: (...args) => uiRuntimeFacade.updateFogUi(...args),
    updateCloudUi: (...args) => uiRuntimeFacade.updateCloudUi(...args),
    updateWaterUi: (...args) => uiRuntimeFacade.updateWaterUi(...args),
    syncRenderFxParallaxUi: (...args) => uiRuntimeFacade.syncRenderFxParallaxUi(...args),
    syncRenderFxLightingUi: (...args) => uiRuntimeFacade.syncRenderFxLightingUi(...args),
    syncRenderFxFogUi: (...args) => uiRuntimeFacade.syncRenderFxFogUi(...args),
    syncRenderFxCloudUi: (...args) => uiRuntimeFacade.syncRenderFxCloudUi(...args),
    syncRenderFxWaterUi: (...args) => uiRuntimeFacade.syncRenderFxWaterUi(...args),
    updatePointLightStrengthLabel: (value = null) => uiRuntimeFacade.updatePointLightStrengthLabel(value),
    updatePointLightIntensityLabel: (value = null) => uiRuntimeFacade.updatePointLightIntensityLabel(value),
    updatePointLightHeightOffsetLabel: (value = null) => uiRuntimeFacade.updatePointLightHeightOffsetLabel(value),
    updatePointLightFlickerLabel: (value = null) => uiRuntimeFacade.updatePointLightFlickerLabel(value),
    updatePointLightFlickerSpeedLabel: (value = null) => uiRuntimeFacade.updatePointLightFlickerSpeedLabel(value),
    updateCursorLightStrengthLabel: () => uiRuntimeFacade.updateCursorLightStrengthLabel(),
    updateCursorLightHeightOffsetLabel: () => uiRuntimeFacade.updateCursorLightHeightOffsetLabel(),
  };
}
