export function buildUniformInputState(deps) {
  const flowDeg = deps.clamp(Number(deps.waterFlowDirectionInput.value), 0, 360);
  const flowRad = (flowDeg * Math.PI) / 180;
  const fog = deps.fogState || null;
  const cloud = deps.cloudState || null;
  const water = deps.waterFxState || null;
  const weather = deps.weatherState || null;

  return {
    shadowBlurPx: deps.clamp(Number(deps.shadowBlurInput.value), 0, 3),
    mapAspect: deps.getMapAspect(),
    heightScale: Number(deps.heightScaleInput.value),
    shadowStrength: Number(deps.shadowStrengthInput.value),
    useShadows: deps.shadowsToggle.checked,
    useParallax: deps.parallaxToggle.checked,
    parallaxStrength: deps.clamp(Number(deps.parallaxStrengthInput.value), 0, 1),
    parallaxBands: Math.round(deps.clamp(Number(deps.parallaxBandsInput.value), 2, 256)),
    useFog: fog ? fog.useFog : deps.fogToggle.checked,
    fogMinAlpha: fog ? fog.fogMinAlpha : deps.clamp(Number(deps.fogMinAlphaInput.value), 0, 1),
    fogMaxAlpha: fog ? fog.fogMaxAlpha : deps.clamp(Number(deps.fogMaxAlphaInput.value), 0, 1),
    fogFalloff: fog ? fog.fogFalloff : deps.clamp(Number(deps.fogFalloffInput.value), 0.2, 4),
    fogStartOffset: fog ? fog.fogStartOffset : deps.clamp(Number(deps.fogStartOffsetInput.value), 0, 1),
    useVolumetric: deps.volumetricToggle.checked,
    volumetricStrength: deps.clamp(Number(deps.volumetricStrengthInput.value), 0, 1),
    volumetricDensity: deps.clamp(Number(deps.volumetricDensityInput.value), 0, 2),
    volumetricAnisotropy: deps.clamp(Number(deps.volumetricAnisotropyInput.value), 0, 0.95),
    volumetricLength: Math.round(deps.clamp(Number(deps.volumetricLengthInput.value), 8, 160)),
    volumetricSamples: Math.round(deps.clamp(Number(deps.volumetricSamplesInput.value), 4, 24)),
    pointFlickerEnabled: deps.pointFlickerToggle.checked,
    pointFlickerStrength: deps.clamp(Number(deps.pointFlickerStrengthInput.value), 0, 1),
    pointFlickerSpeed: deps.clamp(Number(deps.pointFlickerSpeedInput.value), 0.1, 12),
    pointFlickerSpatial: deps.clamp(Number(deps.pointFlickerSpatialInput.value), 0, 4),
    useClouds: cloud ? cloud.useClouds : deps.cloudToggle.checked,
    cloudCoverage: cloud ? cloud.cloudCoverage : deps.clamp(Number(deps.cloudCoverageInput.value), 0, 1),
    cloudSoftness: cloud ? cloud.cloudSoftness : deps.clamp(Number(deps.cloudSoftnessInput.value), 0.01, 0.35),
    cloudOpacity: cloud ? cloud.cloudOpacity : deps.clamp(Number(deps.cloudOpacityInput.value), 0, 1),
    cloudScale: cloud ? cloud.cloudScale : deps.clamp(Number(deps.cloudScaleInput.value), 0.5, 8),
    cloudSpeed1: cloud ? cloud.cloudSpeed1 : deps.clamp(Number(deps.cloudSpeed1Input.value), -0.3, 0.3),
    cloudSpeed2: cloud ? cloud.cloudSpeed2 : deps.clamp(Number(deps.cloudSpeed2Input.value), -0.3, 0.3),
    cloudSunParallax: cloud ? cloud.cloudSunParallax : deps.clamp(Number(deps.cloudSunParallaxInput.value), 0, 2),
    cloudUseSunProjection: cloud ? cloud.cloudUseSunProjection : deps.cloudSunProjectToggle.checked,
    useWaterFx: water ? water.useWaterFx : deps.waterFxToggle.checked,
    waterFlowDownhill: water ? water.waterFlowDownhill : deps.waterFlowDownhillToggle.checked,
    waterFlowInvertDownhill: water ? water.waterFlowInvertDownhill : deps.waterFlowInvertDownhillToggle.checked,
    waterFlowDebug: water ? water.waterFlowDebug : deps.waterFlowDebugToggle.checked,
    waterFlowDirX: water ? water.waterFlowDirX : Math.cos(flowRad),
    waterFlowDirY: water ? water.waterFlowDirY : Math.sin(flowRad),
    waterLocalFlowMix: water ? water.waterLocalFlowMix : deps.clamp(Number(deps.waterLocalFlowMixInput.value), 0, 1),
    waterDownhillBoost: water ? water.waterDownhillBoost : deps.clamp(Number(deps.waterDownhillBoostInput.value), 0, 4),
    waterFlowStrength: water ? water.waterFlowStrength : deps.clamp(Number(deps.waterFlowStrengthInput.value), 0, 0.15),
    waterFlowSpeed: water ? water.waterFlowSpeed : deps.clamp(Number(deps.waterFlowSpeedInput.value), 0, 2.5),
    waterFlowScale: water ? water.waterFlowScale : deps.clamp(Number(deps.waterFlowScaleInput.value), 0.5, 14),
    waterShimmerStrength: water ? water.waterShimmerStrength : deps.clamp(Number(deps.waterShimmerStrengthInput.value), 0, 0.2),
    waterGlintStrength: water ? water.waterGlintStrength : deps.clamp(Number(deps.waterGlintStrengthInput.value), 0, 1.5),
    waterGlintSharpness: water ? water.waterGlintSharpness : deps.clamp(Number(deps.waterGlintSharpnessInput.value), 0, 1),
    waterShoreFoamStrength: water ? water.waterShoreFoamStrength : deps.clamp(Number(deps.waterShoreFoamStrengthInput.value), 0, 0.5),
    waterShoreWidth: water ? water.waterShoreWidth : deps.clamp(Number(deps.waterShoreWidthInput.value), 0.4, 6),
    waterReflectivity: water ? water.waterReflectivity : deps.clamp(Number(deps.waterReflectivityInput.value), 0, 1),
    waterTintColor: water ? water.waterTintColor : deps.hexToRgb01(deps.waterTintColorInput.value),
    waterTintStrength: water ? water.waterTintStrength : deps.clamp(Number(deps.waterTintStrengthInput.value), 0, 1),
    weatherType: weather ? weather.type : "clear",
    weatherIntensity: weather ? weather.intensity : 0,
    weatherWindDirX: weather ? weather.windDirX : 1,
    weatherWindDirY: weather ? weather.windDirY : 0,
    weatherWindSpeed: weather ? weather.windSpeed : 0,
    weatherLocalModulation: weather ? weather.localModulation : 0,
    useCursorLight: deps.cursorLightModeToggle.checked && (deps.cursorLightState ? deps.cursorLightState.active : null),
  };
}
