import { createMapLightingAssemblyRuntime } from "../gameplay/mapLightingAssemblyRuntime.js";

export function createMapLightingAssemblyRuntimeDeps(deps) {
  return {
    pointLightSetup: {
      pointLights: deps.pointLights,
      clamp: deps.clamp,
      splatSize: deps.splatSize,
      selectRadiusPx: deps.selectRadiusPx,
      defaultFlicker: deps.defaultFlicker,
      defaultFlickerSpeed: deps.defaultFlickerSpeed,
      nextPointLightId: deps.nextPointLightId,
      hexToRgb01: deps.hexToRgb01,
      bakePointLightsTexture: deps.bakePointLightsTexture,
      schedulePointLightBake: deps.schedulePointLightBake,
      isPointLightLiveUpdateEnabled: deps.isPointLightLiveUpdateEnabled,
      updateLightEditorUi: deps.updateLightEditorUi,
      requestOverlayDraw: deps.requestOverlayDraw,
      setStatus: deps.setStatus,
      parsePointLightsPayload: deps.parsePointLightsPayload,
      serializePointLightsPayload: deps.serializePointLightsPayload,
      tauriInvoke: deps.tauriInvoke,
      isAbsoluteFsPath: deps.isAbsoluteFsPath,
      joinFsPath: deps.joinFsPath,
      invokeTauri: deps.invokeTauri,
      showSaveFilePicker: deps.showSaveFilePicker,
      normalizeMapFolderPath: deps.normalizeMapFolderPath,
      downloadTextFile: deps.downloadTextFile,
      getCurrentMapFolderPath: deps.getCurrentMapFolderPath,
      tryLoadJsonFromUrl: deps.tryLoadJsonFromUrl,
      clearPointLightsLoadInput: deps.clearPointLightsLoadInput,
      openPointLightsLoadInput: deps.openPointLightsLoadInput,
      setSaveButtonText: deps.setSaveButtonText,
      syncPointLightsStateToStore: deps.syncPointLightsStateToStore,
      setTimeout: deps.setTimeout,
      clearTimeout: deps.clearTimeout,
    },
    mapLifecycleSetup: {
      defaultMapFolder: deps.defaultMapFolder,
      defaultMapFolderCandidates: deps.defaultMapFolderCandidates,
      defaultPlayer: deps.defaultPlayer,
      normalizeMapFolderPath: deps.normalizeMapFolderPath,
      syncMapPathInput: deps.syncMapPathInput,
      syncMapStateToStore: deps.syncMapStateToStore,
      getSettingsDefaults: deps.getSettingsDefaults,
      defaultLightingSettings: deps.defaultLightingSettings,
      defaultParallaxSettings: deps.defaultParallaxSettings,
      defaultInteractionSettings: deps.defaultInteractionSettings,
      defaultFogSettings: deps.defaultFogSettings,
      defaultCloudSettings: deps.defaultCloudSettings,
      defaultWaterSettings: deps.defaultWaterSettings,
      defaultSwarmSettings: deps.defaultSwarmSettings,
      applyLightingSettings: deps.applyLightingSettings,
      applyParallaxSettings: deps.applyParallaxSettings,
      applyInteractionSettings: deps.applyInteractionSettings,
      applyFogSettings: deps.applyFogSettings,
      applyCloudSettings: deps.applyCloudSettings,
      applyWaterSettings: deps.applyWaterSettings,
      applySwarmSettings: deps.applySwarmSettings,
      bakePointLightsTexture: deps.bakePointLightsTexture,
      updateLightEditorUi: deps.updateLightEditorUi,
      reseedSwarmAgents: deps.reseedSwarmAgents,
      getSwarmSettings: deps.getSwarmSettings,
      requestOverlayDraw: deps.requestOverlayDraw,
      tryLoadJsonFromUrl: deps.tryLoadJsonFromUrl,
      applySwarmData: deps.applySwarmData,
      applyLoadedNpc: deps.applyLoadedNpc,
      getFileFromFolderSelection: deps.getFileFromFolderSelection,
      tauriInvoke: deps.tauriInvoke,
      isAbsoluteFsPath: deps.isAbsoluteFsPath,
      validateMapFolderViaTauri: deps.validateMapFolderViaTauri,
      joinFsPath: deps.joinFsPath,
      buildMapAssetPath: deps.buildMapAssetPath,
      loadImageFromUrl: deps.loadImageFromUrl,
      loadImageFromFile: deps.loadImageFromFile,
      applyMapImages: deps.applyMapImages,
      rebuildMovementField: deps.rebuildMovementField,
      setStatus: deps.setStatus,
      serializeLightingSettings: deps.serializeLightingSettings,
      serializeParallaxSettings: deps.serializeParallaxSettings,
      serializeInteractionSettings: deps.serializeInteractionSettings,
      serializeFogSettings: deps.serializeFogSettings,
      serializeCloudSettings: deps.serializeCloudSettings,
      serializeWaterSettings: deps.serializeWaterSettings,
      serializeSwarmData: deps.serializeSwarmData,
      serializeNpcState: deps.serializeNpcState,
      confirm: deps.confirm,
      pickMapFolderViaTauri: deps.pickMapFolderViaTauri,
      invokeTauri: deps.invokeTauri,
      showDirectoryPicker: deps.showDirectoryPicker,
    },
  };
}

export function createMapLightingSetupRuntime(deps) {
  return createMapLightingAssemblyRuntime(createMapLightingAssemblyRuntimeDeps(deps));
}
