export function createRenderSupportAssemblyRuntime(deps) {
  return {
    gl: deps.gl,
    getFlowMapTex: deps.getFlowMapTex,
    clamp: deps.clamp,
    rebuildFlowMapTexturePrecompute: deps.rebuildFlowMapTexturePrecompute,
    getHeightImageData: deps.getHeightImageData,
    getHeightSize: deps.getHeightSize,
    getWaterSettings: deps.getWaterSettings,
    getShadowSize: deps.getShadowSize,
    getShadowRawTex: deps.getShadowRawTex,
    getShadowBlurTex: deps.getShadowBlurTex,
    getShadowRawFbo: deps.getShadowRawFbo,
    getShadowBlurFbo: deps.getShadowBlurFbo,
    getShadowProgram: deps.getShadowProgram,
    getShadowUniforms: deps.getShadowUniforms,
    getHeightTex: deps.getHeightTex,
    getLightingSettings: deps.getLightingSettings,
    getShadowMapScale: deps.getShadowMapScale,
    getCloudNoiseTex: deps.getCloudNoiseTex,
    createCloudNoiseImageRender: deps.createCloudNoiseImageRender,
    uploadCloudNoiseTextureRender: deps.uploadCloudNoiseTextureRender,
  };
}

export function createMapSupportAssemblyRuntime(deps) {
  return {
    defaultMapFolder: deps.defaultMapFolder,
    windowEl: deps.windowEl,
    applyMapSizeChangeIfNeeded: deps.applyMapSizeChangeIfNeeded,
    resetCamera: deps.resetCamera,
    extractImageData: deps.extractImageData,
    uploadImageToTexture: deps.uploadImageToTexture,
    rebuildFlowMapTexture: deps.rebuildFlowMapTexture,
    syncMapStateToStore: deps.syncMapStateToStore,
    getPointLightBakeWorker: deps.getPointLightBakeWorker,
    clamp: deps.clamp,
    getNormalsImageData: deps.getNormalsImageData,
    setNormalsImageData: deps.setNormalsImageData,
    setHeightImageData: deps.setHeightImageData,
    setSlopeImageData: deps.setSlopeImageData,
    setWaterImageData: deps.setWaterImageData,
    getSplatSize: deps.getSplatSize,
    getHeightSize: deps.getHeightSize,
    getNormalsSize: deps.getNormalsSize,
    getSplatTex: deps.getSplatTex,
    getNormalsTex: deps.getNormalsTex,
    getHeightTex: deps.getHeightTex,
    getWaterTex: deps.getWaterTex,
    getHeightImageData: deps.getHeightImageData,
    swarmZMax: deps.swarmZMax,
  };
}
