export function createRuntimeSupportMethodsRuntime(runtimeSupportFacade) {
  return {
    createShader: (type, src) => runtimeSupportFacade.createShader(type, src),
    createProgram: (vsSrc, fsSrc) => runtimeSupportFacade.createProgram(vsSrc, fsSrc),
    createTexture: () => runtimeSupportFacade.createTexture(),
    createLinearTexture: () => runtimeSupportFacade.createLinearTexture(),
    uploadImageToTexture: (tex, image) => runtimeSupportFacade.uploadImageToTexture(tex, image),
    rebuildFlowMapTexture: () => runtimeSupportFacade.rebuildFlowMapTexture(),
    ensureShadowTargets: () => runtimeSupportFacade.ensureShadowTargets(),
    renderShadowPipeline: (params) => runtimeSupportFacade.renderShadowPipeline(params),
    createCloudNoiseImage: (size = 128) => runtimeSupportFacade.createCloudNoiseImage(size),
    uploadCloudNoiseTexture: () => runtimeSupportFacade.uploadCloudNoiseTexture(),
    normalizeMapFolderPath: (path) => runtimeSupportFacade.normalizeMapFolderPath(path),
    tauriInvoke: (...args) => runtimeSupportFacade.tauriInvoke(...args),
    isAbsoluteFsPath: (path) => runtimeSupportFacade.isAbsoluteFsPath(path),
    joinFsPath: (folder, fileName) => runtimeSupportFacade.joinFsPath(folder, fileName),
    buildMapAssetPath: (folder, fileName) => runtimeSupportFacade.buildMapAssetPath(folder, fileName),
    invokeTauri: (command, args) => runtimeSupportFacade.invokeTauri(command, args),
    toAbsoluteFileUrl: (path) => runtimeSupportFacade.toAbsoluteFileUrl(path),
    pickMapFolderViaTauri: () => runtimeSupportFacade.pickMapFolderViaTauri(),
    validateMapFolderViaTauri: (folderPath) => runtimeSupportFacade.validateMapFolderViaTauri(folderPath),
    applyMapImages: (splatImage, normalsImage, heightImage, slopeImage, waterImage) =>
      runtimeSupportFacade.applyMapImages(splatImage, normalsImage, heightImage, slopeImage, waterImage),
    syncPointLightWorkerMapData: () => runtimeSupportFacade.syncPointLightWorkerMapData(),
    getFileFromFolderSelection: (files, fileName) => runtimeSupportFacade.getFileFromFolderSelection(files, fileName),
    tryLoadJsonFromUrl: (path) => runtimeSupportFacade.tryLoadJsonFromUrl(path),
    loadImageFromUrl: (url) => runtimeSupportFacade.loadImageFromUrl(url),
    loadImageFromFile: (file) => runtimeSupportFacade.loadImageFromFile(file),
    getMapImageRuntime: () => runtimeSupportFacade.getMapImageRuntime(),
    normalize3: (x, y, z) => runtimeSupportFacade.normalize3(x, y, z),
    sampleNormalAtMapPixel: (pixelX, pixelY) => runtimeSupportFacade.sampleNormalAtMapPixel(pixelX, pixelY),
    sampleHeightAtMapPixel: (pixelX, pixelY) => runtimeSupportFacade.sampleHeightAtMapPixel(pixelX, pixelY),
    sampleHeightAtMapCoord: (mapX, mapY) => runtimeSupportFacade.sampleHeightAtMapCoord(mapX, mapY),
    computeSwarmDirectionalShadow: (mapX, mapY, sourceHeight, lightDir, blockedShadowFactor) =>
      runtimeSupportFacade.computeSwarmDirectionalShadow(mapX, mapY, sourceHeight, lightDir, blockedShadowFactor),
    hasLineOfSightToLight: (surfaceX, surfaceY, surfaceH, lightX, lightY, lightH, heightScaleValue) =>
      runtimeSupportFacade.hasLineOfSightToLight(
        surfaceX,
        surfaceY,
        surfaceH,
        lightX,
        lightY,
        lightH,
        heightScaleValue,
      ),
  };
}
